export  const _COLORS = {
  // trello web Color
  Trello_BlackColor: "#212121",
  Trello_WhiteColor: "#FFFFFF",
  Trello_LiteWhiteColor: "#F1F1F1",
  Trello_ExtraLiteWhiteColor: "#FCFCFC",
  Trello_LightWhiteColor: "#DDDDDD",
  Trello_LightGrayColor: "#D9D9D9",
  Trello_LightGrayLineColor: "#DBDBDB",
 
  Trello_ExtraLightGrayColor: "#A1A1A1",
  Trello_minLiteGrayColor: "#EFF2F2",
  Trello_ExtraLiteGrayColor: "#92929D",
  Trello_ExtraminLiteGrayColor: "#979797",
  Trello_MediumGrayColor: "#ABACAD",
  Trello_GrayColor: "#CED5D7",
  Trello_VeryLightGrayColor: "#B7C2B7",
  Trello_lightGreenColor: "#8AFBA5",
  Trello_ExtralightGreenColor: "#3DD598",
  Trello_GreenColor: "#45B742",
  Trello_minDarkGreenColor: "#E9F2E9",
  Trello_DarkGreenColor: "#309E63",
  Trello_MostLiteGreyColor: "#F5F5F5",
  Trello_TransparentColor: "transparent",
  Trello_LightOrange: "#FFEFE3",
  Trello_DarkOrange: "#F48444",
  Trello_yellow: "#FFA800",
  Trello_mostLightGreenColor: "#E9F2E9",
  Trello_BlueColor: "#336FC3",
  Trello_mostLightBlueColor: "#E7F1FF",
  Trello_redColor: "#D30000",
  Trello_ExtraDarkGreen: "#309E63",
  Trello_lightRedColor: "#FF5A5A",
  Trello_MediumGreenColor: "#D7FFE0",
  Trello_MidLightGreenColor: "#45B7410B",
};
